package com.cinema.model.enums;

public enum ErrorCode {
    USER_NOT_FOUND,
    USER_ALREADY_EXIST,
    USER_BANNED,
    USER_SUSPENDED,
    INVALID_USER_STATUS,

    EMAIL_ALREADY_EXIST,
    EMAIL_BELONGS_TO_BANNED_USER,

    TICKET_NOT_FOUND,
    TICKET_ALREADY_EXIST,
    INVALID_TICKET_STATE,
    RESERVATION_EXPIRED,

    PAYMENT_FAILED,
    NO_DEFAULT_PAYMENT_METHOD,

    ACCESS_DENIED,
    UNAUTHENTICATED,

    INTERNAL_SERVER_ERROR
}
